apiVersion: v1
stringData: 
{{- if .Values.alertmanagerConfig }}
  alertmanager.yaml: |
{{ toYaml .Values.alertmanagerConfig | indent 4 }}
{{- end }}
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-cie-collector
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
    release: cceaddon-cie-collector
  name: alertmanager
  namespace: monitoring
type: Opaque