apiVersion: v1
kind: Service
metadata:
  name: grafana-ais
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
        "type":"public",
        "bandwidth_name":"test-grafana",
        "bandwidth_size":5,
        "bandwidth_sharetype":"PER",
        "eip_type":"5_bgp"
      }'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: grafana-service
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  
