# README: Need to create csi-disk-ssd storage class first. 
prometheus:
  prometheusSpec:
    resources: # .Values.prometheus.prometheusSpec.resources 
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 2Gi
    retention: "1h" # .Values.prometheus.prometheusSpec.retention | quote
    replicas: 1 # .Values.prometheus.prometheusSpec.replicas
    scrapeInterval: "20s" # .Values.prometheus.prometheusSpec.scrapeInterval
    scrapeTimeout: "10s" # .Values.prometheus.prometheusSpec.scrapeTimeout
    shards: 2 # .Values.prometheus.prometheusSpec.shards
    storageSpec: 
      volumeClaimTemplate:
        metadata:
          annotations:
            everest.io/disk-volume-type: SSD
          labels:
            app: prometheus
          name: pvc
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: csi-disk-ssd
    thanos:
      resources: # .Values.prometheus.prometheusSpec.thanos.resources
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi

prometheusRule:
  - name: test-rule-ais
    rules:
    - alert: NodeUnschedulable
      expr: kube_node_spec_unschedulable == 1
      for: 40s
      labels:
        severity: critical
      annotations:
        summary: "Node {{ $labels.node }} is unschedulable"
        description: "Node {{ $labels.node }} has been unschedulable for more than 40 seconds."

alertmanagerConfig:
  global:
    smtp_smarthost: 'smtp.gmail.com:587'
    smtp_from: 'chan1992241@gmail.com'
    smtp_auth_username: 'chan1992241@gmail.com'
    smtp_auth_password: smtppassword
    smtp_require_tls: true
    resolve_timeout: 1m

  route:
    receiver: 'gmail-notifications'

  receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: chan1992241@gmail.com
        from: chan1992241@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: chan1992241@gmail.com
        auth_identity: chan1992241@gmail.com
        auth_password: smtppassword
        send_resolved: true
    - name: 'null'
    - name: FMGateway
      webhook_configs:
        - url: >-
            http://flask-alert-webhook.alert-service-dev.svc.cluster.local:8080/aistest
