apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-ais
  labels:
    app: github-runner-ais
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-ais
  template:
    metadata:
      labels:
        app: github-runner-ais
    spec:
      containers:
      - name: github-runner-ais
        imagePullPolicy: Always #use local kind image
        image: swr.ap-southeast-3.myhuaweicloud.com/test-fq/github-runner:label
        env:
        - name: GITHUB_OWNER
          valueFrom:
            secretKeyRef:
              name: github-secret-huawei-ais
              key: GITHUB_OWNER
        - name: GITHUB_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: github-secret-huawei-ais
              key: GITHUB_REPOSITORY
        - name: GITHUB_PERSONAL_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret-huawei-ais
              key: GITHUB_PERSONAL_TOKEN
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: data
          mountPath: /work/
      - name: dind 
        image: docker:24.0.6-dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
          - name: data
            mountPath: /work/
      volumes:
      - name: docker-graph-storage 
        emptyDir: {}
      - name: data
        emptyDir: {}

      
