apiVersion: v1
stringData: 
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'chan1992241@gmail.com'
      smtp_auth_username: 'chan1992241@gmail.com'
      smtp_auth_password: smtppassword
      smtp_require_tls: true
      resolve_timeout: 1m

    route:
      receiver: 'gmail-notifications'

    receivers:
      - name: 'gmail-notifications'
        email_configs:
        - to: chan1992241@gmail.com
          from: chan1992241@gmail.com
          smarthost: smtp.gmail.com:587
          auth_username: chan1992241@gmail.com
          auth_identity: chan1992241@gmail.com
          auth_password: smtppassword
          send_resolved: true
      - name: 'null'
      - name: FMGateway
        webhook_configs:
          - url: >-
              http://fastapi-alert-webhook.monitoring.svc.cluster.local:8080/fmgateway?amo_name=sub-AROTest-az-dev&system_name=ocp&ems_name=sub-AROTest-az-dev&ems_ip=10.84.46.132&site_code=sub-AROTest-az-dev&network_type=IT
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-cie-collector
    meta.helm.sh/release-namespace: monitoring
  # creationTimestamp: "2024-08-14T02:45:42Z"
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
    release: cceaddon-cie-collector
  name: alertmanager
  namespace: monitoring
  # resourceVersion: "432028"
  # uid: a87ed933-ea18-4232-a46e-ba764d9ba3f9
type: Opaque