apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: operator-prometheus
  name: operator-prometheus
  namespace: monitoring
spec:
  groups:
  - name: CCEKubeNodeNotReady
    rules:
    - alert: CCEKubeNodeNotReady
      annotations:
        message: '{{ $labels.node }} has been unready for more than 15 minutes.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodenotready
      expr: |
        kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0
      for: 1m
      labels:
        notification_channel: fmgateway
        namespace: '{{ $labels.namespace }}'
        prometheus: openshift-monitoring/k8s
        severity: warning
        amo_name: <AMO_NAME_LABEL_CONFIG>
        node: 'Node-{{ $labels.node }}'
        system_name: 'ocp'
        ems_name: <EMS_NAME_LABEL_CONFIG>
        ems_ip: <EMS_IP_LABEL_CONFIG>
        site_code: <SITE_CODE_LABEL_CONFIG>
        node_ip: ''
        network_type: 'IT'