meshName: common
namespace: istio-system
istioIngressservice:
  ports:
    - name: http2
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
istioIngressserviceAnnotations:
  kubernetes.io/elb.class: "union"
  kubernetes.io/elb.autocreate: '{
    "type":"inner"
  }'
meshNamespaces:
  - alert
jaegerMemoryMaxTraces: 10000
jaegerSamplingRate: 80.0
# prometheusIngressHost: "common-prometheus-staging.chanjinyeelengzai.xyz"