apiVersion: v1
kind: Secret
metadata:
  name: github-username-password
stringData:
  username: github-username
  password: github-personal-token
  SWR_AK: xxx
  SWR_SK: xxx
  BUILD_IMG: swr.xxx.myhuaweicloud.com/xxx/xxx
  KUBECONFIG: # base 64 encoded kubeconfig intranet-access
