# https://github.com/jenkinsci/kubernetes-operator/blob/master/cicd/jobs/k8s.jenkins
# Current State need to manual change agent image to jenkins/inbound-agent:latest
# According to this commit, it use jenkins/inbound-agent:3248.v65ecb_254c298-4 https://github.com/jenkinsci/kubernetes-operator/commit/061995a65ca4a6edb8e7a50fa5ea9f9446c393e1
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "4246.v5a_12b_1fe120e" # Need to use latest version
    - name: workflow-job
      version: "1426.v2ecb_a_a_42fd46"
    - name: workflow-aggregator
      version: "596.v8c21c963d92d"
    - name: git
      version: "5.2.2"
    - name: job-dsl
      version: "1.87"
    - name: configuration-as-code
      version: "1810.v9b_c30a_249a_4c"
    - name: kubernetes-credentials-provider
      version: "1.262.v2670ef7ea_0c5"
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:jdk17
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      credentialType: usernamePassword
      credentialID: github-username-password
      targets: "jenkins/cicd/*.groovy"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/oversampling/Algorint.git
  seedJobAgentImage: "jenkins/inbound-agent:latest"    
