name: 3. Alert Service Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - uat
        - staging
        - sit
        - dev

env: 
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  # KUBE_API_SERVER: ${{ secrets.KUBE_API_SERVER }}
  # KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
  # KUBE_CA_CERT: ${{ secrets.KUBE_CA_CERT }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  ALARM_URL: ${{ secrets.ALARM_URL }}
  RESTGW_PWD: ${{ secrets.RESTGW_PWD }}
  RESTGW_USER: ${{ secrets.RESTGW_USER }}

jobs:
  deploy_istio:
    runs-on: debian
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'latest'

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0        
        
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ env.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        # echo "${{ env.KUBE_CA_CERT }}" > $HOME/.kube/ca.crt
        # kubectl config set-cluster k8s --server=${{ env.KUBE_API_SERVER }}  --certificate-authority=$HOME/.kube/ca.crt  --embed-certs=true --kubeconfig=$HOME/.kube/config
        # kubectl config set-credentials admin --token=${{ env.KUBE_TOKEN }} --kubeconfig=$HOME/.kube/config
        # kubectl config set-context k8s --cluster=k8s --user=admin --kubeconfig=$HOME/.kube/config
        # kubectl config use-context k8s --kubeconfig=$HOME/.kube/config
        # kubectl get pods --all-namespaces
        kubectl version

    - name: Change Alarm URL in deployment
      run: | 
        sed -i "s|<ALARM_URL>|${{ env.ALARM_URL }}|g" restgw/kubernetes/deployment.yaml
        sed -i "s|<RESTGW_PWD>|${{ env.RESTGW_PWD }}|g" restgw/kubernetes/deployment.yaml
        sed -i "s|<RESTGW_USER>|${{ env.RESTGW_USER }}|g" restgw/kubernetes/deployment.yaml
        # cat restgw/kubernetes/deployment.yaml
    
    - name: Apply Alert Service Deployment
      run: |
        # cat restgw/kubernetes/deployment.yaml
        kubectl apply -n alert -f restgw/kubernetes/deployment.yaml
    
    - name: Apply Ingress for Alert Service
      run: |
        cat restgw/kubernetes/ingress.yaml
        kubectl apply -f restgw/kubernetes/ingress.yaml
    