# Change secret to AIS.
name: 6-Testing

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - uat
        - staging
        - dev
        - sit

env:
  HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
  HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
  PASSWORD: ${{ secrets.ECS_ROOT_PWD }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  deploy-cce-monitoring-helm:
    name: CIE Reconfiguration
    runs-on: debian
    environment: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v4
      name: Package step

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: latest
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Plan Terraform
      working-directory: ${{ github.workspace }}/terraform
      id: plan
      run: |
        terraform init
        terraform workspace select -or-create ${{ env.ENVIRONMENT }} 
        export KUBECONFIG=$HOME/.kube/config
        KUBE_CONFIG=$(terraform output -raw kube-config)
        echo $KUBE_CONFIG > $HOME/.kube/config
        kubectl version