name: CCE Monitoring Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - cce-uat
        - cce-sit
        - cce-prod

env: 
  HELM_REPO: 'helm'
  HELM_TEMPLATE: 'helm template'
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  # HELM_REPO_URL: ''
  CCE_MONITORING_HELM_CHART: 'kube-prometheus-stack'
  CCE_MONITORING_HELM_RELEASE_NAME: 'cce-monitoring'
  CCE_MONITORING_HELM_NAMESPACE: 'cce-monitoring'   

jobs:
  deploy-cce-monitoring-setup:
    name: Deploy CCE Monitoring Setup
    runs-on: [self-hosted, debian]
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        with:
          version: latest

      - name: Setup Dev Cluster Secrets
        run: |
          mkdir -p $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo ${{ secrets.KUBE_CONFIG_AIS }} | base64 -d > $KUBECONFIG
          kubectl version

      - name: Helm Template
        run: |
          helm dependency update prometheus/$CCE_MONITORING_HELM_CHART
          helm template prometheus/$CCE_MONITORING_HELM_CHART --namespace $CCE_MONITORING_HELM_NAMESPACE --values prometheus/$CCE_MONITORING_HELM_CHART/values.yaml --output-dir prometheus/$CCE_MONITORING_HELM_CHART/output
          cat prometheus/$CCE_MONITORING_HELM_CHART/output/$CCE_MONITORING_HELM_CHART/templates/prometheus/prometheus.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: prometheus/kube-prometheus-stack
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
