name: CIE Cleanup Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - uat
        - staging
        
env:
  HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
  HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
  PASSWORD: ${{ secrets.ECS_ROOT_PWD }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: debian
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Destroy Terraform
      working-directory: ${{ github.workspace }}/terraform
      id: plan
      run: |
        terraform init
        terraform workspace select -or-create ${{ env.ENVIRONMENT }} 
        TF_VAR_secret_key=$HW_SECRET_KEY TF_VAR_access_key=$HW_ACCESS_KEY TF_VAR_project_ID=$PROJECT_ID terraform destroy --auto-approve -var-file="./${{ env.ENVIRONMENT }}/${{ env.ENVIRONMENT }}.tfvars"
