name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
env: 
  ENVIRONMENT: ${{ github.event.inputs.environment }}
jobs:
  greet:
    runs-on: docker

    steps:
    - name: Send greeting
      run: echo "${{ env.ENVIRONMENT }}"
