name: Deploy Istio

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - uat
        - staging
    inputs:
      namespace:
        type: choice
        description: Namespace
        options:
        - project-microservice 
        - project-istio-microservice

jobs:
  deploy_istio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: Configure kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        export KUBECONFIG=$HOME/.kube/config
        if [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
          echo "${{ secrets.KUBE_CONFIG_AIS_UAT }}" | base64 -d > $KUBECONFIG
        elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
          echo "${{ secrets.KUBE_CONFIG_AIS_STAGING }}" | base64 -d> $KUBECONFIG
        else
          echo "Invalid environment selection"
          exit 1
        fi
        kubectl version

    - name: Set up Istioctl
      run: |
        curl -sL https://istio.io/downloadIstioctl | ISTIO_VERSION=1.22.0 sh -
        export PATH=$HOME/.istioctl/bin:$PATH
        istioctl version

    - name: Install Istio
      run: |
        istioctl install --set profile=default -y -f istio/istio-ais/operator.yaml
        kubectl create namespace ${{ github.event.inputs.namespace }} || true
        kubectl label namespace ${{ github.event.inputs.namespace }} usergroup=${{ github.event.inputs.namespace }} --overwrite
        kubectl get namespace ${{ github.event.inputs.namespace }} -o jsonpath='{.metadata.labels}'

    


    