name: Deploy Istio

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - uat
        - staging
      namespace:
        type: choice
        description: Namespace
        options:
        - istio-sytem
env: 
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  ISTIO_RELEASE_NAME: istiod
  ISTIO_RELEASE_NAMESPACE: istio-system
  ISTIO_CHART_HELM_CHART_NAME: istio/istiod

jobs:
  deploy_istio:
    runs-on: debian

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: Configure kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: 'latest'
            
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        export KUBECONFIG=$HOME/.kube/config
        if [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
          echo "${{ secrets.KUBE_CONFIG_AIS_UAT }}" | base64 -d > $KUBECONFIG
        elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
          echo "${{ secrets.KUBE_CONFIG_AIS_STAGING }}" | base64 -d> $KUBECONFIG
        else
          echo "Invalid environment selection"
          exit 1
        fi
        kubectl version  

    - name: Install Istio Base
      run: |
        helm repo add istio https://istio-release.storage.googleapis.com/charts
        helm upgrade --install istio-base istio/base -n ${{ env.ISTIO_RELEASE_NAMESPACE }} --set defaultRevision=default --create-namespace
        
    - name: Install Istiod
      run: |
        helm upgrade --install istiod istio/istiod -n ${{ env.ISTIO_RELEASE_NAMESPACE }} --values istio/istio-ais/${{ env.ENVIRONMENT }}/istiod.${{ env.ENVIRONMENT }}.yaml

    - name: Install Istio Ingress Gateway
      run: |
        helm upgrade --install istio-ingress istio/gateway -n ${{ env.ISTIO_RELEASE_NAMESPACE }} --values istio/istio-ais/${{ env.ENVIRONMENT }}/ingress.${{ env.ENVIRONMENT }}.yaml

    - name: Label namespace
      run: |
        kubectl create namespace default || true
        kubectl label namespace default istio-injection- istio.io/rev=v1 --overwrite

    - name: Install Kiali
      run: |
        helm repo add kiali https://kiali.org/helm-charts
        helm upgrade --install --namespace istio-system --create-namespace kiali-operator kiali/kiali-operator
        
    - name: Install Kiali CR
      run: |
        kubectl apply -f istio/istio-ais/${{ env.ENVIRONMENT }}/kiali.cr.${{ env.ENVIRONMENT }}.yaml
    
    - name: Install Jaeger
      run: |
        kubectl apply -f istio/istio-ais/${{ env.ENVIRONMENT }}/jaeger.${{ env.ENVIRONMENT }}.yaml
    
    - name: Setup Ingress and Virtual Service
      run: |
        kubectl apply -n default -f istio/istio-ais/${{ env.ENVIRONMENT }}/ingress-gateway.${{ env.ENVIRONMENT }}.yaml

    - name: Create Sample Application
      run: |
        kubectl apply -n default -l version!=v2,version!=v3 -f https://raw.githubusercontent.com/istio/istio/release-1.23/samples/bookinfo/platform/kube/bookinfo.yaml

    