name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - name: Package step
      run: |
        echo "hello"
        echo "package"
  build:
    needs: package
    runs-on: arc-runner-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: swr.${{ secrets.PROJECT }}.myhuaweicloud.com
        username: ${{ secrets.PROJECT }}@${{ secrets.SWR_AK }}
        password: ${{ secrets.SWR_SK }}
    - name: List All File
      run: "ls -la"
    - name: Build and push
      uses: docker/build-push-action@v5 # Build and push to SWR
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: "swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/gra-jy:${{ github.run_id }}"
    - name: Inspect
      run: |
        docker image inspect swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/gra-jy:${{ github.run_id }}
    - name: Push
      run: "docker push swr.${{ secrets.PROJECT }}.myhuaweicloud.com/${{ secrets.ORGANIZATION }}/gra-jy:${{ github.run_id }}"
  
  deploy:
    needs: build
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        with:
          version: latest
      - name: get CCE Cluster info
        run: |
          mkdir -p $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > $KUBECONFIG
          sed -i "s/gra-demo-image/swr.${{ secrets.PROJECT }}.myhuaweicloud.com\/${{ secrets.ORGANIZATION }}\/gra-jy:${{ github.run_id }}/g" k8s.yaml
          kubectl version
          kubectl apply -f k8s.yaml
