apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep-alert
    service: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep-alert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-alert
  template:
    metadata:
      labels:
        app: sleep-alert
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin-alert
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin-alert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-alert
      version: v1
  template:
    metadata:
      labels:
        app: httpbin-alert
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kong/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80