apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: hw-istio-system
  name: kiali
spec:
  auth:
    strategy: "anonymous"  # Using login strategy
  deployment:
    accessible_namespaces:
      - "hw-istio-system"  # Kiali will monitor only the istio-system namespace
      # - "default"  # Kiali will monitor the project-microservice namespace
      - "hw-microservice-1" # Kiali will monitor the project-microservice namespace
    service_type: LoadBalancer  # Use LoadBalancer service type for Kiali
    service_annotations:  # Add annotations to the Kiali service
      kubernetes.io/elb.class: union
      kubernetes.io/elb.autocreate: '{
          "type":"public",
          "bandwidth_name":"test-kiali",
          "bandwidth_size":5,
          "bandwidth_sharetype":"PER",
          "eip_type":"5_bgp"
        }'
  server:
    web_root: "/kiali"  # The root path where Kiali will be accessible
  external_services:
    istio:
      url_service_version: "http://istiod-huawei.istio-system.svc:15014/version"
      components:
        pilot:
          namespace: istio-system  # Ensure Kiali integrates with istiod in the same namespace
    prometheus:
      url: "http://prometheus-operated.monitoring.svc:9090"  # Prometheus URL in the monitoring namespace
    tracing:
      enabled: true
      namespace: hw-istio-system
      service: tracing
  istio_namespace: "hw-istio-system"  # Specifies the namespace where Istio is installed
